tweetstream.rb:8:in `block in <main>': uninitialized constant ActiveRecord (NameError)
	from /Users/pfh/.rvm/gems/ruby-2.1.5/gems/em-twitter-0.3.5/lib/em-twitter/connection.rb:297:in `call'
	from /Users/pfh/.rvm/gems/ruby-2.1.5/gems/em-twitter-0.3.5/lib/em-twitter/connection.rb:297:in `invoke_callback'
	from /Users/pfh/.rvm/gems/ruby-2.1.5/gems/em-twitter-0.3.5/lib/em-twitter/connection.rb:66:in `post_init'
	from /Users/pfh/.rvm/gems/ruby-2.1.5/gems/eventmachine-1.0.7/lib/em/connection.rb:58:in `block in new'
	from /Users/pfh/.rvm/gems/ruby-2.1.5/gems/eventmachine-1.0.7/lib/em/connection.rb:49:in `instance_eval'
	from /Users/pfh/.rvm/gems/ruby-2.1.5/gems/eventmachine-1.0.7/lib/em/connection.rb:49:in `new'
	from /Users/pfh/.rvm/gems/ruby-2.1.5/gems/eventmachine-1.0.7/lib/eventmachine.rb:679:in `bind_connect'
	from /Users/pfh/.rvm/gems/ruby-2.1.5/gems/eventmachine-1.0.7/lib/eventmachine.rb:649:in `connect'
	from /Users/pfh/.rvm/gems/ruby-2.1.5/gems/em-twitter-0.3.5/lib/em-twitter/client.rb:51:in `connect'
	from /Users/pfh/.rvm/gems/ruby-2.1.5/gems/em-twitter-0.3.5/lib/em-twitter/client.rb:30:in `block in connect'
	from /Users/pfh/.rvm/gems/ruby-2.1.5/gems/em-twitter-0.3.5/lib/em-twitter/client.rb:29:in `tap'
	from /Users/pfh/.rvm/gems/ruby-2.1.5/gems/em-twitter-0.3.5/lib/em-twitter/client.rb:29:in `connect'
	from /Users/pfh/.rvm/gems/ruby-2.1.5/gems/tweetstream-2.6.1/lib/tweetstream/client.rb:413:in `connect'
	from /Users/pfh/.rvm/gems/ruby-2.1.5/gems/tweetstream-2.6.1/lib/tweetstream/client.rb:404:in `block in start'
	from /Users/pfh/.rvm/gems/ruby-2.1.5/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `call'
	from /Users/pfh/.rvm/gems/ruby-2.1.5/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run_machine'
	from /Users/pfh/.rvm/gems/ruby-2.1.5/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run'
	from /Users/pfh/.rvm/gems/ruby-2.1.5/gems/tweetstream-2.6.1/lib/tweetstream/client.rb:403:in `start'
	from /Users/pfh/.rvm/gems/ruby-2.1.5/gems/tweetstream-2.6.1/lib/tweetstream/daemon.rb:48:in `block in start'
	from /Users/pfh/.rvm/gems/ruby-2.1.5/gems/daemons-1.2.2/lib/daemons/application.rb:265:in `call'
	from /Users/pfh/.rvm/gems/ruby-2.1.5/gems/daemons-1.2.2/lib/daemons/application.rb:265:in `block in start_proc'
	from /Users/pfh/.rvm/gems/ruby-2.1.5/gems/daemons-1.2.2/lib/daemons/daemonize.rb:84:in `call'
	from /Users/pfh/.rvm/gems/ruby-2.1.5/gems/daemons-1.2.2/lib/daemons/daemonize.rb:84:in `call_as_daemon'
	from /Users/pfh/.rvm/gems/ruby-2.1.5/gems/daemons-1.2.2/lib/daemons/application.rb:269:in `start_proc'
	from /Users/pfh/.rvm/gems/ruby-2.1.5/gems/daemons-1.2.2/lib/daemons/application.rb:295:in `start'
	from /Users/pfh/.rvm/gems/ruby-2.1.5/gems/daemons-1.2.2/lib/daemons/controller.rb:69:in `run'
	from /Users/pfh/.rvm/gems/ruby-2.1.5/gems/daemons-1.2.2/lib/daemons.rb:193:in `block in run_proc'
	from /Users/pfh/.rvm/gems/ruby-2.1.5/gems/daemons-1.2.2/lib/daemons/cmdline.rb:88:in `call'
	from /Users/pfh/.rvm/gems/ruby-2.1.5/gems/daemons-1.2.2/lib/daemons/cmdline.rb:88:in `catch_exceptions'
	from /Users/pfh/.rvm/gems/ruby-2.1.5/gems/daemons-1.2.2/lib/daemons.rb:192:in `run_proc'
	from /Users/pfh/.rvm/gems/ruby-2.1.5/gems/tweetstream-2.6.1/lib/tweetstream/daemon.rb:47:in `start'
	from /Users/pfh/.rvm/gems/ruby-2.1.5/gems/tweetstream-2.6.1/lib/tweetstream/client.rb:136:in `filter'
	from /Users/pfh/.rvm/gems/ruby-2.1.5/gems/tweetstream-2.6.1/lib/tweetstream/client.rb:105:in `track'
	from tweetstream.rb:11:in `<main>'
